export const groceryList = [
  {
    id: "0",
    title: "Steak",
    done: false,
    added: true,
  },
  {
    id: "1",
    title: "Abalone",
    done: false,
    added: true,
  },
  {
    id: "2",
    title: "Beef brisket $25.13",
    done: false,
    added: false,
  },
  {
    id: "3",
    title: "Beef tendon",
    done: false,
    added: false,
  },
  {
    id: "4",
    title: "White carrot radish",
    done: false,
    added: false,
  },
  {
    id: "5",
    title: "Red wine",
    done: false,
    added: false,
  },
  {
    id: "6",
    title: "Sweet potato good for eyes",
    done: false,
    added: false,
  },
  {
    id: "7",
    title: "Black beans canned",
    done: false,
    added: false,
  },
  {
    id: "8",
    title: "Broccoli (cholesterol, cancer)",
    done: false,
    added: false,
  },
  {
    id: "9",
    title: "Egg plant",
    done: false,
    added: false,
  },
  {
    id: "10",
    title: "Beets",
    done: false,
    added: false,
  },
  {
    id: "11",
    title: "Dragon fruit",
    done: false,
    added: false,
  },
  {
    id: "12",
    title: "Salmon wild caught fish",
    done: false,
    added: false,
  },
  {
    id: "13",
    title: "Avocado",
    done: false,
    added: false,
  },
  {
    id: "14",
    title: "Corn",
    done: false,
    added: false,
  },
  {
    id: "15",
    title: "Saba",
    done: false,
    added: false,
  },
  {
    id: "16",
    title: "Banana",
    done: false,
    added: false,
  },
  {
    id: "17",
    title: "Ginger",
    done: false,
    added: false,
  },
  {
    id: "18",
    title: "Cauliflower",
    done: false,
    added: false,
  },
  {
    id: "19",
    title: "Buy fish fm seatobag?",
    done: false,
    added: false,
  },
  {
    id: "20",
    title: "ABC sundry shop",
    done: false,
    added: false,
  },
  {
    id: "21",
    title: "Jif 1.95 each",
    done: false,
    added: false,
  },
  {
    id: "22",
    title: "Chocolate ",
    done: false,
    added: false,
  },
  {
    id: "23",
    title: "Turpentine",
    done: false,
    added: false,
  },
  {
    id: "24",
    title: "Blade for calluses",
    done: false,
    added: false,
  },
];
